# Generated by Django 2.2 on 2020-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='No Alias', max_length=45),
            preserve_default=False,
        ),
    ]
