# Generated by Django 2.2 on 2020-12-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0003_user_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alias',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
    ]
