# Generated by Django 2.2 on 2020-12-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shakedown_io', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='client',
        ),
    ]
