# Generated by Django 2.2 on 2020-12-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakedown_io', '0004_file_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
