# Generated by Django 2.2 on 2020-12-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakedown_io', '0005_file_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='price',
            field=models.IntegerField(),
        ),
    ]
